/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
 * Generated on: 11-Dec-2021 17:30:43
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : No
 * Arithmetic        : fixed
 * Numerator         : s16,14 -> [-2 2)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,29 -> [-8 8)  (auto determined)
 *   Product         : s31,29 -> [-2 2)  (auto determined)
 *   Accumulator     : s33,29 -> [-8 8)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
const int BL = 11;
const int16_T B[11] = {
    25286,  -9892,  -2676,   8929, -10057,   8127,  -5046,   2175,   -220,
     -675,   1377
};
