/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
 * Generated on: 11-Dec-2021 23:24:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 56
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Mathworks\extern\include\tmwtypes.h 
 */
const int BL = 56;
const int16_T B[56] = {
      -24,    177,    581,    442,   -243,   -219,    376,     37,   -485,
      237,    481,   -584,   -274,    911,   -184,  -1064,    869,    862,
    -1653,   -147,   2310,  -1200,  -2535,   3328,   1940,  -6968,    158,
    20198,  20198,    158,  -6968,   1940,   3328,  -2535,  -1200,   2310,
     -147,  -1653,    862,    869,  -1064,   -184,    911,   -274,   -584,
      481,    237,   -485,     37,    376,   -219,   -243,    442,    581,
      177,    -24
};
