/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
 * Generated on: 11-Dec-2021 20:13:05
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 56
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,14 -> [-2 2)
 * Input             : s16,3 -> [-4096 4096)
 * Filter Internals  : Full Precision
 *   Output          : s34,17 -> [-65536 65536)  (auto determined)
 *   Product         : s31,17 -> [-8192 8192)  (auto determined)
 *   Accumulator     : s34,17 -> [-65536 65536)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
const int BL = 56;
const int16_T B[56] = {
     -649,    397,   -471,    511,   -501,    426,   -276,     42,    275,
     -667,   1115,  -1591,   2057,  -2465,   2760,  -2882,   2773,  -2372,
     1630,   -504,  -1029,   2977,  -5322,   8016, -10968,  14000, -16672,
    17112,  17112, -16672,  14000, -10968,   8016,  -5322,   2977,  -1029,
     -504,   1630,  -2372,   2773,  -2882,   2760,  -2465,   2057,  -1591,
     1115,   -667,    275,     42,   -276,    426,   -501,    511,   -471,
      397,   -649
};
