/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
 * Generated on: 11-Dec-2021 20:13:05
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 56
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,14 -> [-2 2)
 * Input             : s16,3 -> [-4096 4096)
 * Filter Internals  : Full Precision
 *   Output          : s34,17 -> [-65536 65536)  (auto determined)
 *   Product         : s31,17 -> [-8192 8192)  (auto determined)
 *   Accumulator     : s34,17 -> [-65536 65536)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
#include "stdint.h"

